TOPDIR ?= ../..
include $(TOPDIR)/.config

$(BTN_4WAY_SUPPORT)_SRC       += hardware/btn_4way/btn_4way.c
$(BTN_4WAY_SUPPORT)_ECMD_SRC  += hardware/btn_4way/ecmd.c


##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

